---
title: "current season"
output: html_document
date: "2022-10-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse); library(nbastatR); library(lubridate)
```

```{r teams}

picks_01 <- c("Nikola Jokic", "Fred VanVleet", "Jimmy Butler", "Scottie Barnes", "Desmond Bane", "Al Horford", "Tre Jones", "Jaren Jackson Jr.", "Tari Eason", "Alex Caruso", "Jaden Ivy", "Aaron Gordon", "Jerami Grant")
picks_02 <- c("Luka Doncic", "Bam Adebayo", "Donovan Mitchell", "Kristaps Porzingis", "Terry Rozier", "Collin Sexton", "Mitchell Robinson", "Jabari Smith", "Cameron Johnson", "Russell Westbrook", "Malcolm Brogdon", "Patrick Williams", "Walker K")
picks_03 <- c("Giannis Antetokounmpo", "Ja Morant", "Domantas Sabonis", "CJ McCollum", "Khris Middleton", "Christian Wood", "Wendell Carter Jr.", "Kyle Lowry", "Saddiq Bey", "Harrison Barnes", "Jaden McDaniels", "Derrick White", "Bogdan Bogdanovic")
picks_04 <- c("Joel Embiid", "Dejounte Murray", "Rudy Gobert", "Nikola Vucevic", "Tyrese Maxey", "Jalen Green", "Lauri Markkanen", "Keegan Murray", "Robert Williams III", "Kyle Kuzma", "Nic Claxton", "Benedict", "Dillon Brooks")
picks_05 <- c("Kevin Durant", "Kyrie Irving", "Darius Garland", "De'Aaron Fox", "Michael Porter Jr.", "Keldon Johnson", "Julius Randle", "Buddy Hield", "Onyeka Okongwu", "Jalen Smith", "Mike Conley", "Bones Hyland", "Isaiah Stewart")
picks_06 <- c("Karl-Anthony Towns", "Kawhi Leonard", "Jrue Holiday", "Chris Paul", "Ben Simmons", "Mikal Bridges", "Paolo", "Kevin Porter Jr.", "Herbert Jones", "Isaiah Jackson", "Isaiah Hartenstein", "Robert Covington", "Jordan Clarkson")
picks_07 <- c("Jayson Tatum", "Anthony Edwards", "Pascal Siakam", "Shai Gilgeous-Alexander", "John Collins", "Jalen Brunson", "D'Angelo Russell", "Clint Capela", "Tobias Harris", "De'Anthony Melton", "Cole Anthony", "Dorian Finney-Smith", "Steven Adams")
picks_08 <- c("Stephen Curry", "LeBron James", "Zion Williamson", "Deandre Ayton", "Jamal Murray", "Franz Wagner", "Jakob Poeltl", "RJ Barrett", "Spencer Dinwiddie", "John Wall", "Norman Powell", "JaVale McGee", "Matisse Thybulle")
picks_09 <- c("Damian Lillard", "Paul George", "DeMar DeRozan", "Jaylen Brown", "Jonas Valanciunas", "Jusuf Nurkic", "Marcus Smart", "Gary Trent Jr.", "Ivica Zubac", "Ayo Dosunmu", "Jarred Vanderbilt", "Brook Lopez", "Richaun Holmes")
picks_10 <- c("Anthony Davis", "Devin Booker", "Cade Cunningham", "Evan Mobley", "Josh Giddey", "OG Anunoby", "Draymond Green", "Andrew Wiggins", "Brandon Clarke", "Bobby Portis", "Luguentz Dort", "Kevin Love", "Reggie Jackson")
picks_11 <- c("James Harden", "Trae Young", "Bradley Beal", "Myles Turner", "Brandon Ingram", "Jordan Poole", "Tyler Herro", "Anfernee Simons", "Gordon Hayward", "James Wiseman", "Josh Hart", "Kevin Huerter", "Aleksej Pokusevski")
picks_12 <- c("Tyrese Haliburton", "LaMelo Ball", "Zach LaVine", "Jarrett Allen", "Klay Thompson", "Alperen Sengun", "Devin Vassell", "P.J. Washington", "Monte Morris", "Kelly Oubre Jr.", "Kelly Olynyk", "Mo Bamba", "Santi Aldama")

picks <- c(picks_01,picks_02,picks_03,picks_04,picks_05,picks_06,picks_07,picks_08,picks_09,picks_10,picks_11,picks_12)

```

```{r}
sched <- 
  current_schedule() %>%
  # After season start for 2023
  filter(dateGame >= as.Date("2022-10-18"))

pull_games <- 
  sched %>%
  filter(dateGame < lubridate::today())
```

```{r}
games <- 
  box_scores(
    game_ids = pull_games$idGame,
    box_score_types = "traditional", 
    result_types = "player"
  ) %>%
  unnest(cols = c(dataBoxScore)) %>%
  

comps <- 
  games %>%
  select(
    game_id = idGame, player_id = idPlayer, player_name = namePlayer, 
    minutes = minExact ,pts,fg3m,pctFG,pctFT,ast,treb,stl,blk,tov
  ) %>%
  left_join(
    sched %>% select(game_id = idGame, game_date = dateSlugGame),
    by = "game_id"
  ) %>%
  mutate(
    game_date = ymd(game_date),
    game_week = floor_date(ymd(game_date), unit="week",week_start=1)
  ) %>%
  filter(player_name %in% picks) %>%
  mutate(
    team = case_when(
      player_name %in% picks_01 ~ "team_01",
      player_name %in% picks_02 ~ "team_02_jub",
      player_name %in% picks_03 ~ "team_03",
      player_name %in% picks_04 ~ "team_04_chad",
      player_name %in% picks_05 ~ "team_05",
      player_name %in% picks_06 ~ "team_06",
      player_name %in% picks_07 ~ "team_07_ezra",
      player_name %in% picks_08 ~ "team_08",
      player_name %in% picks_09 ~ "team_09",
      player_name %in% picks_10 ~ "team_10",
      player_name %in% picks_11 ~ "team_11",
      player_name %in% picks_12 ~ "team_12"
    )
  )
  
```


```{r}
team_comp <-
  comps %>%
  group_by(team) %>%
  summarize_at(vars(pts:tov), list(~sum(.))) %>%
  pivot_longer(pts:tov,names_to = "category") %>% 
  group_by(category) %>%
  mutate(
    rank = cume_dist(value),
    n_teams = n_distinct(team),
    n_beats = rank * n_teams
  )


team_comp %>%
  mutate(team = str_remove(team,"^team_")) %>%
  ggplot(aes(x = category, y = n_beats)) +
  facet_grid(vars(team), scales = "free") +
  geom_col() +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  theme_minimal()
```
```{r}
game_weeks <-
  comps %>%
  group_by(team, game_week) %>%
  summarize_at(vars(pts:tov),list(~sum(., na.rm = T))) %>%
  pivot_longer(pts:tov, names_to = "stat", values_to = "value")


game_weeks %>%
  ggplot(aes(x = game_week, y = value, color = team)) +
  geom_line() +
  geom_point() +
  facet_grid(vars(stat), scales = "free") +
  paletteer::scale_color_paletteer_d("colorBlindness::paletteMartin") +
  theme_minimal()
```

